### ISSUE TITLE
Storage location of certificates

### ISSUE THREAD

**Issue by mhoster83** [iobroker-community-adapters/ioBroker.acme#103]
Can someone give me a hint, where the adapter stores the received certificate files? Thanks

**Comment by mcm1957** [comment]
As far as I know acme adapter used @iobroker/webserver component and the certificate istatored at state system.certificates.

But I'm not sure. So keep open - untila a confirmation or correction is received.

**Comment by mhoster83** [comment]
Thank you very much, that worked out
