### ISSUE TITLE
stopAdaptersOnSamePort doesn't work

### ISSUE THREAD

**Issue by raintonr** [iobroker-community-adapters/ioBroker.acme#12]
@GermanBluefox I think this logic is trying to be too smart for it's own good. I do not like it at all for a number of reasons:

1. It fails on my system here because there is an old web instance running, which uses the old Let's Encrypt method which does not have the listen port defined in `port` but of course defined in `lePort` and thus isn't found.
2. There is absolutely no way to guarantee other adapters won't have similar config and be missed. I note, for example, that you changed the name of the port config in this adatper to be `port` for consistency but that's only because you know about this. It will be very hard to police this. I don't like that you made that change - I prefer verbose names as much as possible for clarity.
3. To avoid the above, if you think users can't be trusted to properly configure ports (see point 5) there really should be a mechanism for port management with a nice API or whatever for adapters to use to check ports, request port release, notify port release, etc, etc. I doubt this is going to happen any time soon (or even ever?).
4. I really do not like the idea of one adapter stopping another like this. There is no safeguard to absolutely guarantee that an adapter would be restarted if ACME crashed.
5. If someone has configured their system to use the same ports for two different adapters then IMHO that is a big mistake. I think the an adapter should fail with the `address already in use` message so the system owner can find an alternate port.
6. If you absolutely insist that this function should stay (and why would we keep something with all the above issues?) then I think there should be an option to disable it, and if enabled, there should be logging all over that start/stop logic to let a system owner know what's going on. Imagine the frustration of not knowing why an adapter has restarted seemingly randomly.

And the most obvious reason: the challenge server only ever runs on the public facing port 80 (or where that has been forwarded to) which is for insecure HTTP. If one is using ACME that implies they also want to use HTTPS, not HTTP, and therefore would never have anything else running on the same insecure HTTP port anyway!

**Comment by GermanBluefox** [comment]
Why we should do something to complex if it could be simple? :)
Best practice is "port" for the port number and `leEnabled/lePort` for letsencrypt ports. Just now `leEnabled/lePort` will be replaced by your adapter, but `port` will be required from now during review. And we will make a requests to other adapters to change name of port and bind address to `port` and `bind` (and may be to `v6bind`).
Latest Admin version has JSON-Config type port. It checks if the port is free (by name of course)

**Comment by GermanBluefox** [comment]
> Why we should do something to complex if it could be simple? :) Best practice is `port` for the port number and `leEnabled/leUpdate/leCheckPort` for letsencrypt ports. Just now `leEnabled/leUpdate/leCheckPort` will be replaced by your adapter, but `port` will be required from now during review. And we will make a requests to other adapters to change name of port and bind address to `port` and `bind` (and may be to `v6bind`). Latest Admin version has JSON-Config type port. It checks if the port is free (by name of course)

**Comment by raintonr** [comment]
@GermanBluefox - Guess I've been outvoted :cry:
