### ISSUE TITLE
Cannot start the acme Controller - instance system.adapter.acme.0 terminated with code 1 (JS_CONTROLLER_STOPPED)

### ISSUE THREAD

**Issue by itsmehenning** [iobroker-community-adapters/ioBroker.acme#146]
Cannot start the acme Controller.

Error message in iobroker:
instance system.adapter.acme.0 terminated with code 1 (JS_CONTROLLER_STOPPED)

js-controller: 6.0.11
Node.js: v20.18.1

**Comment by mcm1957** [comment]
Please add version of adapter.
Please add a complete log with loglevel set to DEBUG

**Comment by mcm1957** [comment]
As important information is missing lets close here.

Please feel free to create a new issue and add version information and complete log with level DEBUG.

**Comment by itsmehenning** [comment]
latest Version v1.0.3
There is no logfile. I tested it on with silly or debug level.
