### ISSUE TITLE
Status Tab not working with Admin 7.4.3

### ISSUE THREAD

**Issue by SVallant** [iobroker-community-adapters/ioBroker.acme#149]
**Describe the bug**  
"Tab" Status show only "moving" blue line, in previous version certs were listed. 

**To Reproduce**  
1. Go to instances => ACME => Settings => Status
2. See error

**Expected behavior**  
show a list of certs

**Screenshots & Logfiles**  
![grafik](https://github.com/user-attachments/assets/06fcc496-ac12-42a4-b633-486344fdcc81)

**Versions:**  
 - Adapter version: 1.0.3
 - JS-Controller version: 7.0.4 
 - Node version: 20.18.1 
 - Operating system: Ubuntu LTS 24.04
 
 **edit**
 is there another way to see the certs ?

**Comment by mcm1957** [comment]
This is an admin issue.

**Comment by SVallant** [comment]
ok
opened https://github.com/ioBroker/ioBroker.admin/issues/2848
and closed here

**Comment by SVallant** [comment]
sorry i have to reopen it:
now with Version V1.0.4 i get this message in "status"-Tab
`Cannot import from custom/customComponents.js: [object Event]`

![grafik](https://github.com/user-attachments/assets/0bbdf182-3ec7-4a86-ba9e-b97911eb371a)


-     Adapter version: 1.0.4
-     JS-Controller version: 7.0.4
-     Node version: 20.18.1
-     Operating system: Ubuntu LTS 24.04

**Comment by mcm1957** [comment]
BF via TG gepingt

**Comment by SVallant** [comment]
solved with V1.0.5 Thank you
