### ISSUE TITLE
Add some sort of status to admin collections screen

### ISSUE THREAD

**Issue by raintonr** [iobroker-community-adapters/ioBroker.acme#15]
It would be nice to see the status of each collection in the admin interface. Something that shows:

- Has certificate been ordered and is it good?
- If certificate is valid, when renewal is due?
- If certificate is bad, when the last order was attempted and that order failed?

Etc..?

Where to store this info between runs would be up for debate. Maybe more meta objects for each instance? Or a state for each collection?

**Comment by GermanBluefox** [comment]
I can implement  Control, that can show this info in acme settings dialog. Is it OK?

**Comment by raintonr** [comment]
> I can implement Control...

What do you mean by that?

I could add code in the renewal process that sets some flags or records messages or whatever when errors occur. Do you think such messages belong in a one-state-per-collection object or to be dumped collectively as an object into a meta state similar to how the account info is currently stored (quick though would be that the latter is easier)?

**Comment by GermanBluefox** [comment]
![image](https://user-images.githubusercontent.com/4582016/227988232-81cf83f8-7c5e-4959-af5f-a295dcaab50e.png)

**Comment by GermanBluefox** [comment]
"Staging" says nothing to me, but "test" I understand. 
Staging is test, isn't it?

**Comment by raintonr** [comment]
Consistency!

Use 'staging' everywhere or use 'testing' everywhere.

Given the ACME package and CAs all use the term 'staging' it's my preference.

IMHO 'staging' is pretty obvious it's not for production use.

**Comment by raintonr** [comment]
Functionally looks OK so merged, but...

- Inconsistent terms: 'testing' and 'staging'.
- Inconsistent styling. Main & Challenges tabs differ from Collections & Status tabs.

**Comment by mcm1957** [comment]
@raintonr 

Is this issue fixed?

If yes then it should be closed.
If no please remove fixed label

**Comment by raintonr** [comment]
It works, but I do not like that @GermanBluefox used different terminology to that used by the CA. I note he didn't change the wording though so probably has more important things to worry about.
